= About This Repository

This repository contains the TEI source file, and derived text and HTML files of an ebook posted to https://www.gutenberg.org/[Project Gutenberg]. Like the version posted to Project Gutenberg, this ebook is free from copyright in the U.S. No claim is made about its copyright status outside the U.S.

The version maintained in this repository may be slightly out-of-sync with the version maintained at Project Gutenberg. Mostly, fixes will be made first here, and only then reposted to Project Gutenberg. When you encounter any issue in this text, please report it here.

== About This Ebook

|===
|Field |Value

|Title |Aristoteles’ Zielkunde
|Author |Aristoteles (384–322 v. Chr.)
|Publisher |Project Gutenberg, Urbana, Illinois, USA., 2024-12-14
|Publication date |2024-12-14
|Availability |Dit eBoek is voor kosteloos gebruik door iedereen overal, met vrijwel geen beperkingen van welke soort dan ook. U mag het kopiëren, weggeven of hergebruiken onder de voorwaarden van de Project Gutenberg Licentie in dit eBoek of on-line op https://www.gutenberg.org/[www.gutenberg.org]. Dit eBoek is geproduceerd door het on-line gedistribueerd correctieteam op https://www.pgdp.net/[www.pgdp.net]. Bewerking van Aristoteles’ Περὶ ΨυχῆςPeri Psychēs, ook bekend onder de Latijnse titel De Anima.
|PG Ebook Number |https://www.gutenberg.org/ebooks/74894[74894]
|===
